server:
 port: 9080
spring:
 application:
  name: asaauth
 config:
  import: "optional:configserver:http://localhost:8071/"
 datasource:
  url: jdbc:postgresql://127.0.0.1:5432/krdh_aua_db
  #url: jdbc:postgresql://postgres-container:5432/krdh_aua_db
  #url: jdbc:mysql://localhost:3306/krdh_aua_db
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver
  #driver-class-name: com.mysql.cj.jdbc.Driver
 
  
eureka:
 client:
  service-url:
    defaultZone: http://localhost:8090/eureka/
  register-with-eureka: true   # Ensures the service registers itself with Eureka
  fetch-registry: true          # Ensures the service fetches Eureka registry
 instance:
  hostname: localhost           # Replace with actual hostname if needed
uidai_auth_url:  https://rdpreprod.uidai.gov.in/uidauthserver/2.5/
asa_lk: MIIWVkN0fKXYqnHtm8LImBxWphMTZFxt9qaFpRAsVqzUGsJOUjzF91E
ac: STGCEG0001

    