server:
 port: 9080
spring:
 application:
  name: asaauth
 config:
  import: "optional:configserver:http://localhost:8071/"
 datasource:
  url: jdbc:postgresql://localhost:5432/krdh_aua_db
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver