server:
 port: 8081
spring:
 application:
  name: crypto
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
crypto:  
 ac: STGCEG0001
 certIdentifier: 2730942401094b5c
 certPath: 0
 certAlias: 0000840000_sign_30_03_2026_cer
 certExpiryDate: 2026-03-29
 certType: sign
 provider: Luna
 slotPassword: Cegblr@1234
